name: File check
run-name: File Check Run-name
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  check:
    runs-on: ubuntu-latest
    env:
      WHITE_LIST: "piecehealth"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          CHANGED_FILES=$(git diff --name-only $(git merge-base remotes/origin/main HEAD))

          if echo "$CHANGED_FILES" | grep -q --include='*.yml' '^config/locales/generated/'; then
            if echo "$WHITE_LIST" | grep -qw "${{ github.actor }}"; then
              echo "User ${{ github.actor }} is allowed to make changes."
            else
              echo "Error: User ${{ github.actor }} is not authorized to make changes."
              exit 1
            fi
          else
            echo "no changes."
          fi
